/**
 * Regenerates supabase/seed.sql from the default content in src/content/defaults.js.
 * Run with:  npm run seed:generate
 */
import { writeFileSync } from 'node:fs'
import { defaultContent, defaultProjects } from '../src/content/defaults.js'

const sqlString = (value) => `'${String(value).replace(/'/g, "''")}'`
const sqlJson = (value) => `${sqlString(JSON.stringify(value))}::jsonb`

const lines = [
  '-- =============================================================',
  '-- Seed: the content the portfolio shipped with.',
  '-- Generated by scripts/generate-seed.mjs — do not edit by hand.',
  '--',
  '-- Safe to re-run: existing rows are left untouched (ON CONFLICT DO NOTHING),',
  '-- so this will never overwrite edits made in /admin.',
  '-- =============================================================',
  '',
  'insert into public.site_content (key, data) values'
]

const sectionValues = Object.entries(defaultContent).map(
  ([key, data]) => `  (${sqlString(key)}, ${sqlJson(data)})`
)
lines.push(sectionValues.join(',\n'))
lines.push('on conflict (key) do nothing;', '')

lines.push('insert into public.projects (slug, position, featured, data) values')
const projectValues = defaultProjects.map(
  (p) => `  (${sqlString(p.slug)}, ${p.position}, ${p.featured}, ${sqlJson(p.data)})`
)
lines.push(projectValues.join(',\n'))
lines.push('on conflict (slug) do nothing;', '')

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n'))
console.log(
  `Wrote supabase/seed.sql — ${sectionValues.length} sections, ${projectValues.length} projects.`
)
